### ISSUE TITLE
Running On Windows - Invalid Syntax

### ISSUE THREAD

**Issue by Sn3akyP3t3** [xyzroe/ZigStarGW-MT#10]
<root>\ZigStarGW-MT-main\ZigStarGW-MT-main>ZigStarGW-MT.py
Traceback (most recent call last):
  File "<root>\ZigStarGW-MT-main\ZigStarGW-MT-main\ZigStarGW-MT.py", line 13, in <module>
    from ui import main, etc
  File "<root>\ZigStarGW-MT-main\ZigStarGW-MT-main\ui\etc.py", line 12, in <module>
    import cc2538_bsl
  File "<root>\ZigStarGW-MT-main\ZigStarGW-MT-main\cc2538_bsl.py", line 1
    ./cc2538-bsl/cc2538-bsl.py
    ^
SyntaxError: invalid syntax

**Comment by xyzroe** [comment]
Windows does not support Unix shortcuts. 
So to run the project, you need to replace cc2538_bsl.py in root folder with cc2538-bsl/cc2538-bsl.py
